package com.hercare.backend.dto.response;

import java.time.LocalDateTime;

import com.hercare.backend.enums.RiskLevel;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Builder;
import lombok.Data;

@Data
@Builder
@Schema(description = "Response containing the PCOD prediction result")
public class PredictionResponse {

    @Schema(description = "Prediction record ID", example = "15")
    private Long id;

    @Schema(description = "Calculated Body Mass Index (BMI)", example = "25.58")
    private Double bmi;

    @Schema(description = "Prediction score generated by the system", example = "78")
    private Integer predictionScore;

    @Schema(description = "Predicted PCOD risk level", example = "HIGH")
    private RiskLevel riskLevel;

    @Schema(description = "Health recommendation based on the prediction", example = "Consult a gynecologist and maintain a healthy lifestyle.")
    private String recommendation;

    @Schema(description = "Date and time when the prediction was generated", example = "2026-07-15T10:30:00")
    private LocalDateTime predictionDate;
}
